spring.application.name=ec-auth

server.port = 8081
spring.datasource.url=jdbc:mysql://localhost:3306/ec_auth
spring.datasource.driver-class-key=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=InSane

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

encryption.key=EC_ENCRYPTION_KEY

jwt.secret=MySuperSecureKeyForJwtTokenGeneration1234567890abcdef
